<?php
/**
 * @file
 * Demo to use any (custom) theme setting or backdrop variable in any of your
 * theme or module style sheets (see https://backdrop.org/project/style_settings).
 */

/**
 * Implements hook_config_info().
 */
function style_settings_demo_config_info() {
  $prefixes['style_settings_demo.settings'] = array(
    'label' => t('Style settings demo'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_init().
 */
function style_settings_demo_init() {
  backdrop_add_css(backdrop_get_path('module', 'style_settings_demo') . '/css/FOO.css', array(
    'group' => CSS_DEFAULT,
    'every_page' => TRUE,
  ));
}

/**
 * Implements hook_menu().
 */
function style_settings_demo_menu() {
  // Here placed in the 'config/SYSTEM' section. Put it in the appropriate
  // section.
  $items['admin/config/system/FOO'] = array(
    'title' => 'FOO',
    'description' => 'FOO Style Settings demo example.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('FOO_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'FOO.admin.inc',
  );
  return $items;
}
